# Generated by Django 4.2.2 on 2023-08-10 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_invoicing_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoicing',
        ),
    ]
