# Generated by Django 4.2.2 on 2023-08-12 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_invoicing_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicing',
            old_name='value',
            new_name='total_value',
        ),
        migrations.RemoveField(
            model_name='invoicing',
            name='client',
        ),
        migrations.RemoveField(
            model_name='invoicing',
            name='date',
        ),
        migrations.RemoveField(
            model_name='invoicing',
            name='title',
        ),
        migrations.RemoveField(
            model_name='invoicing',
            name='type_revenue',
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('type_revenue', models.CharField(choices=[('revenue', 'Revenue'), ('expense', 'Expense')], default='revenue', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('client', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
