# Generated by Django 4.2.2 on 2023-08-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_discounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discounts',
        ),
    ]
