# Generated by Django 4.2.2 on 2023-08-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='total_cart_item',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total_price_item',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Item Price'),
            preserve_default=False,
        ),
    ]
