# Generated by Django 4.2.2 on 2023-08-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_status_remove_cartitem_total_cart_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='total_price_item',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Item Price'),
        ),
    ]
